name: appgam
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: any
  url_launcher: ^6.0.3
  flutter_screenutil: any
  flutter_launcher_icons: ^0.9.2
  fl_chart: ^0.41.0
  file_picker: ^4.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: false
  image_path: "assets/img/logoApp.png"
