name: appgam
description: A new Flutter project.

version: 1.0.9+9

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: any
  url_launcher: ^6.0.3
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.13.1
  fl_chart: any
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  async: ^2.11.0
  rflutter_alert: ^2.0.7
  internet_file: ^1.2.0
  device_info_plus: ^9.1.0
  syncfusion_flutter_pdfviewer: ^20.4.54
  open_filex: ^4.3.4
  flutter_downloader: ^1.11.5
  flutter_file_downloader: ^1.1.4
  image_network: ^2.5.4+1
  cached_network_image: ^3.3.0
  auto_route: ^7.8.1
  auto_size_text: ^3.0.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: false
  image_path: "assets/img/logoApp.png"
